"""add rerank_model to tenant_config

Revision ID: 7f1fbcd6e1db
Revises: 3288c2fdca2d
Create Date: 2026-06-23 17:34:08.958252

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7f1fbcd6e1db"
down_revision: str | Sequence[str] | None = "3288c2fdca2d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Add NOT NULL with a server_default so existing rows backfill, then drop the
    # default so the column matches the model (the app sets it on insert).
    op.add_column(
        "tenant_configs",
        sa.Column("rerank_model", sa.String(length=64), nullable=False, server_default="gpt-4o-mini"),
    )
    op.alter_column("tenant_configs", "rerank_model", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tenant_configs", "rerank_model")
    # ### end Alembic commands ###
