"""add token_usages table

Revision ID: a5d23b86b89f
Revises: b5d5c6a8b4bd
Create Date: 2026-05-24 19:31:52.831929

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a5d23b86b89f"
down_revision: str | Sequence[str] | None = "b5d5c6a8b4bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_usages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.String(length=128), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("channel", sa.String(length=32), nullable=True),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False),
        sa.Column("input_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("cache_read_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("output_cost", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_usages_created_at"), "token_usages", ["created_at"], unique=False)
    op.create_index(op.f("ix_token_usages_request_id"), "token_usages", ["request_id"], unique=False)
    op.create_index(op.f("ix_token_usages_tenant_id"), "token_usages", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_token_usages_thread_id"), "token_usages", ["thread_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_token_usages_thread_id"), table_name="token_usages")
    op.drop_index(op.f("ix_token_usages_tenant_id"), table_name="token_usages")
    op.drop_index(op.f("ix_token_usages_request_id"), table_name="token_usages")
    op.drop_index(op.f("ix_token_usages_created_at"), table_name="token_usages")
    op.drop_table("token_usages")
    # ### end Alembic commands ###
